### ISSUE TITLE
Make it obvious where to get the different artefacts from

### ISSUE THREAD

**Issue by cmungall** [INCATools/kgcl#85]
Related: https://github.com/INCATools/kgcl-rdflib/issues/68

The README and/or the markdown docs under [w3id.org/kgcl/](https://w3id.org/kgcl/) should make it obvious where to go for

- owl
- python
- any other generated artefact

We can also point to the ontology that is browsable on bioportal

Also these don't work:

https://github.com/perma-id/w3id.org/blob/master/kgcl/.htaccess

```
wget https://w3id.org/kgcl/kcgl.owl.ttl
--2024-11-06 13:30:11--  https://w3id.org/kgcl/kcgl.owl.ttl
Resolving w3id.org (w3id.org)... 162.209.11.63
Connecting to w3id.org (w3id.org)|162.209.11.63|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://incatools.github.io/kgcl/kcgl.owl.ttl [following]
--2024-11-06 13:30:12--  https://incatools.github.io/kgcl/kcgl.owl.ttl
Resolving incatools.github.io (incatools.github.io)... 185.199.110.153, 185.199.108.153, 185.199.109.153, ...
Connecting to incatools.github.io (incatools.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-11-06 13:30:12 ERROR 404: Not Found.
```

**Comment by cmungall** [comment]
also: shacl

**Comment by nlharris** [comment]
I don't feel qualified to review this - maybe @gouttegd could take a look?

**Comment by gouttegd** [comment]
> Also these don't work:
> 
> https://github.com/perma-id/w3id.org/blob/master/kgcl/.htaccess

All redirections set forth in `w3id.org` are working for me right now:

* https://w3id.org/kgcl/kgcl.owl.ttl
* https://w3id.org/kgcl/kgcl.context.jsonld
* https://w3id.org/kgcl/kgcl.shacl.ttl
* https://w3id.org/kgcl/kgcl.yaml

It doesn’t look like anything has changed on `w3id.org` nor on KGCL’s own repo, so it might have been a network glitch?

> also: shacl, json-schema

More generally, should we have redirects for all generated artefacts under `project/`? E.g. what about

* `kgcl.xslx`
* `kgcl.graphql`
* `kgcl.schema.json`
* `kgcl.proto`
* `kgcl.shex`
* `kgcl.sql`

?

Related: Generated files under `projects/` were last refreshed in February (d8f0a15), so they do not reflect changes to the model that happened since then (such as 1433c37c2e2cf1b13b09aea21904d3dff03f7897 and e3a139b93a90a411badcfda62f10c0b9297b49fa).

**Comment by nlharris** [comment]
@caufieldjh can you take a look at this please? thanks!

**Comment by cmungall** [comment]
doh, I had a typo in my wget I was doing `https://w3id.org/kgcl/kcgl.owl.ttl` (k**cg**l)

**Comment by nlharris** [comment]
Note that this is a blocker for resubmitting the revised KGCL paper.

**Comment by caufieldjh** [comment]
The w3id's above should work - is the blocker the working URLs or the inclusion of them in the docs?

**Comment by cmungall** [comment]
Docs

**Comment by caufieldjh** [comment]
OK, the W3IDs are in the docs and the README now
